name: Document

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 23

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
                  run_install: true

            - name: Compile
              run: pnpm compile

            - name: Document
              run: pnpm document

            - name: Upload pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./docs/dist
                  name: github-pages
                  retention-days: 1
    deploy:
        name: Deploy
        needs: build
        runs-on: macos-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
