name: Test

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Use Checkout 4
              uses: actions/checkout@v4

            - name: Use Node.js 21
              uses: actions/setup-node@v3
              with:
                  node-version: 21

            - name: Use pnpm 8
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true

            - name: Compile
              run: pnpm compile

            - name: Install again (to fix binary links) # Horrible, but tbh IDK how to make this better for now
              run: pnpm install

            - name: Run tests
              run: pnpm test

            - name: Use Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
